default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: <%= ENV["DB_USERNAME"] %>
  password: <%= ENV["DB_PASSWORD"] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: drive_peek_development

test:
  <<: *default
  database: drive_peek_test

production:
  primary: &primary_production
    <<: *default
    database: drive_peek_production
    username: drive_peek
    password: <%= ENV["DRIVE_PEEK_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: drive_peek_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: drive_peek_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: drive_peek_production_cable
    migrations_paths: db/cable_migrate
