default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: <%= ENV["DB_USERNAME"] %>
  password: <%= ENV["DB_PASSWORD"] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: drive_peek_development

test:
  <<: *default
  database: drive_peek_test

production:
  url: <%= ENV['DATABASE_URL'] %>

cable:
  adapter: postgresql
  url: <%= ENV['DATABASE_URL'] %>

queue:
  adapter: postgresql
  url: <%= ENV['DATABASE_URL'] %>

cache:
  adapter: postgresql
  url: <%= ENV['DATABASE_URL'] %>
